### PR TITLE
Added support for epoch in container IDs

### LINKED ISSUE #119: Container naming assumptions in ``yarn_api`` seem incorrect
According to [`ContainerId`](https://hadoop.apache.org/docs/current/api/org/apache/hadoop/yarn/api/records/ContainerId.html#toString--) API docs, its string representation is constructed according to the following format:

> [...] `container_e*epoch*_*clusterTimestamp*_*appId*_*attemptId*_*containerId*` when epoch is larger than 0 (e.g. container_e17_1410901177871_0001_01_000005). *epoch* is increased when RM restarts or fails over. When epoch is 0, epoch is omitted (e.g. container_1410901177871_0001_01_000005).

https://github.com/dask/knit/blob/24a5e33ab5d6b4235cadf79f7e4244eb9935e9b4/knit/yarn_api.py#L130

It seems that the current version of the code ignores the fact that epoch can be non-zero and therefore could return an empty list of containers, even though there're running containers for a given application.

### PR DESCRIPTION
**Pull request by superbobry**
Closes #119. 

I hesitated to add new tests, as the current integration test setup will most likely lack the epoch part of the container ID. Existing tests for `Knit.get_containers` should pass.

### CODE REVIEW

**Comment by superbobry** [comment]
In fact, I think `get_containers` is broken anyway because it only looks for allocated containers on the same node as AM. A proper fix is probably to store a list of containers as part of the AM state and expose it via py4j.

@mtchib what do you think?

**Comment by martindurant** [comment]
You might be interested in a re-write of knit appearing at https://github.com/jcrist/skein . I don't know if it specifically covers interacting with specific containers (yet), but it is generally better-designed and I expect it to become a robust complete replacement for knit fairly soon.

**Comment by superbobry** [comment]
Thanks for the tip @martindurant, I had a quick look and skein indeed looks very nice. Would you recommend focusing our efforts on it, instead of knit? Or, to put it differently, do you picture skein completely replacing knit for distributing Dask in the near future? :)

**Comment by martindurant** [comment]
Yes, a complete replacement is the hope.

**Pull request closed without merging**
