### PR TITLE
File fixes

### PR DESCRIPTION
**Pull request by martindurant**
Rules:

- files starting with hdfs:// will not be uploaded, but their location will
be absolute. Note that if not including host:port, should look like
hdfs:///path/file

- other files will be put into hdfs_home/.knitDeps/file , where file is the
basename.

### CODE REVIEW

**Comment by martindurant** [comment]
Aiming to fix #104 , #105 , #106

**Comment by jcrist** [comment]
Overall the intention here sounds good to me.

> Note that if not including host:port, should look like `hdfs:///path/file`

Hmmm, I think it'd be easy to forget the third `/`, and three `/` looks weird to me any way. Could you instead interpret `hdfs://path/file` to mean `/path/file` on the current hdfs namenode? Is there a good reason to not do this?

**Comment by martindurant** [comment]
Yes, we could convert hdfs://path to hdfs:///path, it'd be a regex-replace.

**Comment by jcrist** [comment]
Can you add a test for a path that's already on hdfs, and add `hdfs3` to the travis install so that `test_hdfs_home` isn't skipped?

**Pull request merged**
