### PR TITLE
Python 2.6 compatibility fixes

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Removed an unused import which wasn't available in Python 2.6, and modified all string formatting to included a numeric index required by Python 2.6.

### CODE REVIEW

**Comment by mrocklin** [comment]
Should we add `2.6` compatibility testing to travis.ci?

**Comment by NielsZeilemaker** [comment]
Great idea

**Comment by NielsZeilemaker** [comment]
I did a rebase, and managed to get Python 2.6 working on Travis. Had to refactor quite a bit.
The coverage still seems to be broken though, but not due to this pull-request, as shown here https://travis-ci.org/dask/knit/jobs/109468450.

```
--------------- coverage: platform linux2, python 2.7.11-final-0 ---------------
Name                 Stmts   Miss  Cover   Missing
--------------------------------------------------
knit/__init__.py         7      7     0%   1-10
knit/core.py           106    106     0%   1-300
knit/env.py            101    101     0%   1-222
knit/exceptions.py       8      8     0%   1-14
knit/utils.py           32     32     0%   1-86
knit/yarn_api.py        86     86     0%   1-169
--------------------------------------------------

TOTAL                  340    340     0%   

```

**Comment by quasiben** [comment]
@NielsZeilemaker thanks so much for the PR.  Can you rebase against master now and see if the last commit fixes the coverage problem for you.  Also, I'm happy to take over from here if you'd like

**Comment by NielsZeilemaker** [comment]
@quasiben i did a rebase and added a unit-test to keep the coverage up.

**Comment by quasiben** [comment]
Looks great!  Merging now

**Pull request merged**
