### PR TITLE
Fix for -1000 case

### LINKED ISSUE #111: Knit applications fail if files are uploaded in new release.
Using knit at commit 6c2550cd89d55e9f83233db1f53684e33366478f, the following succeeds:

```
knit = Knit(hdfs_home='/tmp/knit')
knit.start('env', env='myenv.zip')
```

Using the new knit 0.2.3 release, the following (should be equivalent) starts the application, but the application fails.

```
knit = Knit(hdfs_home='/tmp/knit')
knit.start('env', files=['myenv.zip'])
```

Note that this succeeds if I omit the `files` kwarg. Also note that the files are uploaded to the proper location on hdfs, and the log lines reference the proper hdfs locations.

For debugging the logs seem to be unhelpful here, I'm not sure if this is just how yarn is or if there is something knit could do to be better for debugging. There are no java tracebacks, the application just fails.

The few lines I found that may help with debugging:

- `directory.info` ends without ever listing the uploaded files. Note that in both the working version and this version the `broken symlinks` line exists.

```
ls -l:
total 20
-rw-------. 1 yarn hadoop  166 Oct 30 12:13 container_tokens
-rwx------. 1 yarn hadoop  704 Oct 30 12:13 default_container_executor_session.sh
-rwx------. 1 yarn hadoop  758 Oct 30 12:13 default_container_executor.sh
lrwxrwxrwx. 1 yarn hadoop   66 Oct 30 12:13 knit.jar -> /hdfs/disk03/hadoop/yarn/local/filecache/166/knit-1.0-SNAPSHOT.jar
-rwx------. 1 yarn hadoop 4901 Oct 30 12:13 launch_container.sh
drwx--x---. 2 yarn hadoop   10 Oct 30 12:13 tmp
find -L . -maxdepth 5 -ls:
8597569075    4 drwx--x---   3 yarn     hadoop       4096 Oct 30 12:13 .
14182360386    0 drwx--x---   2 yarn     hadoop         10 Oct 30 12:13 ./tmp
8597569076    4 -rw-------   1 yarn     hadoop        166 Oct 30 12:13 ./container_tokens
8597569077    4 -rw-------   1 yarn     hadoop         12 Oct 30 12:13 ./.container_tokens.crc
8599231880    8 -rwx------   1 yarn     hadoop       4901 Oct 30 12:13 ./launch_container.sh
8599231881    4 -rw-------   1 yarn     hadoop         48 Oct 30 12:13 ./.launch_container.sh.crc
8599231882    4 -rwx------   1 yarn     hadoop        704 Oct 30 12:13 ./default_container_executor_session.sh
8599231883    4 -rw-------   1 yarn     hadoop         16 Oct 30 12:13 ./.default_container_executor_session.sh.crc
8599231888    4 -rwx------   1 yarn     hadoop        758 Oct 30 12:13 ./default_container_executor.sh
8599231889    4 -rw-------   1 yarn     hadoop         16 Oct 30 12:13 ./.default_container_executor.sh.crc
12884939857 25320 -r-xr-xr-x   1 yarn     hadoop   25925992 Oct 30 12:13 ./knit.jar
broken symlinks(find -L . -maxdepth 5 -type l -ls):

End of LogType:directory.info
```

- The `Container completed ContainerStatus: [...]` line indicates exit code -1000. Googling this code doesn't turn up any results, so I'm not sure what it means.

I'm not sure what else I can do to help debug here. For now I'm relying on a custom build of an older commit.

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #111

### CODE REVIEW

**Comment by martindurant** [comment]
@jcrist , I believe this is correct. I don't see how tests could pass both before and after - perhaps the defaultFS on some systems points to the local disc, but in the particular image used by the tests, all paths are promoted to HDFS? I tested on stand-alone cluster which showed the -1000 error.

**Comment by jcrist** [comment]
I can confirm this fixes my issue. Also not sure how tests passed before.

**Comment by martindurant** [comment]
Merge and release? Could also include the apparently simple fix in #112 (again, can't realistically be tested)

**Comment by jcrist** [comment]
Merge and release sounds good to me. I'll leave #112 up to you, not sure what's best there.

**Comment by martindurant** [comment]
I think setting the memory request for the AM >>300MB is totally reasonable and harmless, since the typical minimum allotment is 1GB anyway. The only alternative fix for that issue is documentation of config changes.

**Pull request merged**
