### PR TITLE
Use PY4j to communicate with the YARN client and master

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Less argument parsing needed + direct contact with app master.
This will hopefully eventually lead to dynamic execution.

### CODE REVIEW

**Comment by mrocklin** [comment]
I'm very excited about this work.  Is there a significant change in latency?

**Comment by NielsZeilemaker** [comment]
@mrocklin not really. Maybe a small increase due to splitting the startup process of the application master into parts. I've also implemented a test_add_containers method which does some dynamic allocation :smile:

**Comment by quasiben** [comment]
@NielsZeilemaker my sincere apology for taking so long to get back to you.  This work is amazing!  Did you switch to the asynchronous AM/RM clients because this removed the need for arg parsing in the AM?

Seriously, this is fantastic.  Do you have any other thoughts before merging ?  

Do you have thoughts about passing logs back to the python through the job ?  I suppose this is what `akka` is for -- is this worth considering ?

**Comment by NielsZeilemaker** [comment]
Hi @quasiben, I've been on a short vacation as well. No worries.

I switched to the async stuff because I removed the need for blocking the python thread while we were waiting for the containers to be allocated. Moreover, most other AM also use the async stuff, so my guess wast that it was more or less the default choice.

It should be more or less ready to be merged. However there are a few weak points. If we lose the connection to the master, you'll get a low of nasty exceptions. Also I would like to refactor the knit core.py and remove the app_id parameter from most functions, because we should be using the connection to the yarnclient/am to implement most of those functions.

**Comment by NielsZeilemaker** [comment]
Btw, the Travis CI integration seems to be broken...

**Comment by koverholt** [comment]
@NielsZeilemaker, I just set Travis CI to build both pushes and PRs, hopefully that will fix things.

**Comment by NielsZeilemaker** [comment]
@quasiben i think its ready to be merged. However, I did change the api quite a bit so have a look if you still agree with all my changes.
Next, we should probably add a callback interface which allows a Python process to be notified whenever a container starts/dies. Shouldn't be too difficult accoring to this: https://www.py4j.org/advanced_topics.html#implementing-java-interfaces-from-python-callback

**Comment by quasiben** [comment]
Merging now.  Thanks @NielsZeilemaker .  I agree with you about noticing container death.  I'll look into kerberos with the help of @steveloughran : https://github.com/steveloughran/kerberos_and_hadoop

**Pull request merged**
