### PR TITLE
Add in dask-yarn, various fixes.

### PR DESCRIPTION
**Pull request by martindurant**
Some re-writing, and inclusion of functionality from https://github.com/dask/dask-yarn

### CODE REVIEW

**Comment by martindurant** [comment]
@quasiben , @mrocklin - I have already put too much into this PR, so your thoughts appreciated on what is here so far.

For the next stage, a CLI like dask-kuberenetes, the obvious route would be to have the scheduler as a container too, rather than a blocking process. There are other ways around this, such as have the CLI start a Cluster (locally blocking; and store the PID), but be able to speak to the generated YARN master to create more processed through further CLI calls. Maybe both should be possible, ... or something else.

**Comment by martindurant** [comment]
@quartox : I have made a number of small changes in this PR. Here is a brief synopsis:
- fold dask-yarn back into knit (this is because I needed to edit both together, and they seem very much part of the same effort to me)
- more thorough treatment of parameters and how they are passed from the dask cluster to knit
- caching of environments both in creation and uploading
- specify user, which defines location of files in HDFS
- extra safeguards and methods to remove all applications, list uploaded envs etc.

I am writing to you as a user of this package "in the wild" and asking for your input on any pain points. Was https://github.com/dask/dask-yarn/issues/17 solved?

**Comment by quartox** [comment]
@martindurant I never got around that error, so I have been stuck without getting anything running on our yarn cluster. I am happy to test out any new changes. I have only about a year of experience running yarn applications but have an interest in working through these bugs for personal development.

The previous improvements to knit (https://github.com/dask/knit/pull/64) required me to hack the conda build script (specifically the jre related environment variables) to create a local conda package to test the changes. I tried using the `setup.py` but it didn't build the jar, though it might be user error. Having a simple script for users to build and install the development version of the knit  would help with testing.

**Comment by martindurant** [comment]
`python setup.py mvn ` should be the command to build the compiled java, with whatever java env you have set up.

**Comment by quartox** [comment]
Using `python setup.py install mvn`, when I try to run a simple test case (the dask-yarn repo example) I get the following error:

```
2017-06-29 08:46:24,583 - knit.env - INFO - Creating new env dask-35d2a1ee201208ae9fca6905fa88ea9e54557b58
2017-06-29 08:46:24,583 - knit.env - INFO - /home/jlord/.conda/envs/dask/lib/python3.5/site-packages/knit-0.2+2.g5dcf8fb.dirty-py3.5.egg/knit/tmp_conda/miniconda/bin/conda create -p 
/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/knit-0.2+2.g5dcf8fb.dirty-py3.5.egg/knit/tmp_conda/miniconda/envs/dask-35d2a1ee201208ae9fca6905fa88ea9e54557b58 --copy -y -q 
dask>=0.14 distributed>=1.16
[...traceback...]
FileNotFoundError: [Errno 2] No such file or directory: '/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/knit-0.2+2.g5dcf8fb.dirty-py3.5.egg/knit/tmp_conda/miniconda/bin/con
da'
distributed.utils - ERROR - 'StreamClosedError' object has no attribute 'real_error'
```

Running my own conda build and conda install from local is the only thing I have found that works.

**Comment by kpweiler** [comment]
migrated here from https://github.com/dask/dask-yarn/issues/17

I grabbed the newest code and manually installed knit. I noticed that if I just go straight through knit and don't use the dask-yarn wrapper, my command seem to run just fine provided I don't try to forward an env to the container(s):


```
from knit import Knit

k = Knit(
    user = 'kweiler',
    nn = "<REDACTED>",
    nn_port = 8020,
    rm = "<REDACTED>",
    rm_port = 8088,
    autodetect = False,
    validate = False
)

cmd = 'ls'
k.start(cmd, num_containers=3
```


This returns successfully (although, it doesn't seem to return the stdout of the ls command to the application container log).

If, instead, I try to provide an environment but run the same command:

```
env_zip = k.create_env(env_name='dev', packages=['dask', 'distributed', 'pandas'])
cmd = 'ls'
k.start(cmd, num_containers=3, env = env_zip)
```

I get 15 kerberos errors (15 max retries) like this:

```
17/07/21 14:18:19 INFO knit.ApplicationMaster$: Running command in container: ls
17/07/21 14:18:19 WARN security.UserGroupInformation: PriviledgedActionException as:kweiler (auth:KERBEROS) cause:javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/07/21 14:18:19 WARN ipc.Client: Exception encountered while connecting to the server : javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/07/21 14:18:19 WARN security.UserGroupInformation: PriviledgedActionException as:kweiler (auth:KERBEROS) cause:java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/07/21 14:18:19 WARN security.UserGroupInformation: PriviledgedActionException as:kweiler (auth:KERBEROS) cause:javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/07/21 14:18:19 WARN ipc.Client: Exception encountered while connecting to the server : javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/07/21 14:18:19 WARN security.UserGroupInformation: PriviledgedActionException as:kweiler (auth:KERBEROS) cause:java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/07/21 14:18:19 INFO retry.RetryInvocationHandler: Exception while invoking getFileInfo of class ClientNamenodeProtocolTranslatorPB over <REDACTED>:8020 after 1 fail over attempts. Trying to fail over immediately.
java.io.IOException: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; Host Details : local host is: "<REDACTED>"; destination host is: "<REDACTED>":8020; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:772)
	at org.apache.hadoop.ipc.Client.call(Client.java:1475)
	at org.apache.hadoop.ipc.Client.call(Client.java:1408)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy9.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:757)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:256)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:104)
	at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2121)
	at org.apache.hadoop.hdfs.DistributedFileSystem$19.doCall(DistributedFileSystem.java:1215)
	at org.apache.hadoop.hdfs.DistributedFileSystem$19.doCall(DistributedFileSystem.java:1211)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1211)
	at io.continuum.knit.Utils$.setUpLocalResource(Utils.scala:24)
	at io.continuum.knit.ApplicationMaster$$anonfun$onContainersAllocated$1.apply(ApplicationMaster.scala:176)
	at io.continuum.knit.ApplicationMaster$$anonfun$onContainersAllocated$1.apply(ApplicationMaster.scala:140)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.continuum.knit.ApplicationMaster$.onContainersAllocated(ApplicationMaster.scala:140)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:292)
Caused by: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:687)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:650)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1524)
	at org.apache.hadoop.ipc.Client.call(Client.java:1447)
	... 25 more
Caused by: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:413)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:560)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:375)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:725)
	... 28 more
Caused by: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
	at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
	at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
	at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
	at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192)
	... 37 more
```

I believe this implies that the trouble is in HDFS auth, not Yarn.

**Comment by martindurant** [comment]
OK @kpweiler , that sounds like progress! So the problem is accessing HDFS from the container: we should probably be generating a delegation token in the app-master and (pass it in)/(arrange the container to ask for it). There is [code around](https://github.com/eBay/Spark/blob/master/yarn/src/main/scala/org/apache/spark/deploy/yarn/AMDelegationTokenRenewer.scala) that does this kind of thing, but maybe better to start off with [simpler descriptions](http://henning.kropponline.de/2016/02/14/a-secure-hdfs-client-example/).

**Comment by kpweiler** [comment]
thanks @martindurant 

I noticed after I posted that indeed my env is making it to HDFS, so I agree, the trouble is in accessing it from the container.

I'll have a look at the code, but I'm not terribly confident in my ability to fix it. I'll probably try to seek some outside help on it.

**Comment by martindurant** [comment]
Do you have hdfs3 installed on your client machine, and can it connect to the name-node? I am wondering whether it is possible to make a delegate token there (currently unimplemented [here](https://github.com/Anaconda-Platform/anaconda-platform/issues/1512)). This is probably not the right want to do it, but I'm interested to know what works.

**Comment by kpweiler** [comment]
@martindurant 

When you say the client machine, do you mean the machine I'm running my python code from, or the cluster machines that run the containers?

I can easily install libhdfs3 on my client machine, but not on the cluster machines that run the containers (at least not easily). It can be done though.

Incidentally - I can't seem to install hdfs3 (or libhdfs3) from my anaconda3 (python 3.6) installation:

```
$ conda install hdfs3
Fetching package metadata .........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - hdfs3 -> libhdfs3 -> boost ==1.60 -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by martindurant** [comment]
It would normally be from the conda-forge channel (`-c conda-forge`). The anaconda version of libhdfs3 is old and needs boost 1.60, which is not built for py36.
I meant on you local machine, where you are calling knit from and run your python code.

**Comment by kpweiler** [comment]
@martindurant 
Cool, I was able to get it installed. Let me know if you create a branch and want me to do some testing. Btw - that unimplemented link doesn't resolve for me. Maybe I can contribute some code if I understand a bit better what you're trying to do?

**Comment by martindurant** [comment]
Specifically, I'm wondering whether the following returns any content:

    import hdfs3
    hdfs = hdfs3.HDFSFileSystem(...)
    hdfs3.lib._lib.hdfsGetDelegationToken(hdfs._handle,  b'user_name')

You should specify the name-node and port from your config (for HA, port is None) and your HDFS user name to HDFSFileSystem.
Also, it's best to set the following env var to the location of your hdfs config, like

    export LIBHDFS3_CONF=/etc/hadoop/conf/hdfs-site.xml

**Comment by kpweiler** [comment]
I'm having some trouble getting this working - I believe I need to do this:

https://github.com/dask/hdfs3/issues/91
(compile libgsasl with gssapi support)

I'll give it a try.

Incidentally, the need to specify one's ticket cache is not something I've seen in other kerberos implementations and is a bit kludgy. I'll have a look at automating that perhaps.

**Comment by martindurant** [comment]
I can confirm that hdfs3 is able to generate delegate tokens following the prescription above (no recompiling required), which potentially opens an avenue for easier auth in containers. Or, rather, it returned *some kind* of binary string.
This was on MIT kerberos, of course...

**Comment by kpweiler** [comment]
Could you paste the code you used to get a delegate token? More specifically, I'm interested if you had to pass:

```pars={'hadoop.security.authentication': 'kerberos'}```

This is the bit that is failing for me.

Additionally, it seems like you're using hdfs3 all over the knit code to interact with hdfs so I don't know why you wouldn't want to use it for auth. Maybe I'm misunderstanding why you think this is a suboptimal approach.

**Comment by martindurant** [comment]
The code is exactly as above. Seemed to work both with and without the extra parameter (which maybe suggests II wasn't really authenticated?). For HA, you may need to pass a full set of parameters like [here](http://hdfs3.readthedocs.io/en/latest/hdfs.html#high-availability-mode).

**Comment by martindurant** [comment]
@kpweiler : I find I can inspect the environment that a container finds by doing things like
```
cmd = ''env | hadoop fs -put - /tmp/testing/out ''
k.start(cmd, num_containers=1)
```
and then looking at the resultant file.
(having previously made the hdfs directory with open permissions)

**Comment by kpweiler** [comment]
@martindurant 

one bit of administrivia: Should We be having this conversation over here:

https://github.com/dask/knit/issues/67

We can move this over there if so - sorry for the confusion on my part.

I don't think the code is exactly as above as hdfs3.HDFSFileSystem doesn't exist. I assume you mean hdfs3.HDFileSystem. It would also be interesting to see what which parameters you're specifying (in place of the "..."). Don't need to see the actual config items, just the parameters.

I think it's also interesting that even after specifying:
`LIBHDFS3_CONF=/etc/hadoop/conf/hdfs-site.xml`
which is definitely where my hdfs conf file lives, hdfs3 still wants to connect to localhost:8020 if I don't give it any configuration:

```
$ wc -l /etc/hadoop/conf/hdfs-site.xml
117 /etc/hadoop/conf/hdfs-site.xml

$ ipython
In [1]: import os
   ...: import hdfs3
   ...:

In [2]: os.environ["LIBHDFS3_CONF"] = "/etc/hadoop/conf/hdfs-site.xml"

In [3]: hdfs3.HDFileSystem()
2017-07-24 16:41:12.742692, p18969, th140657445959488, ERROR Failed to setup RPC connection to "localhost:8020" caused by:
TcpSocket.cpp: 293: HdfsNetworkConnectException: Connect to "localhost:8020" failed: (errno: 111) Connection refused
```

Finally, we should also be having this specific conversation over at the actual hdfs3 project git. Right?

**Comment by martindurant** [comment]
The code was like the following, running from an edge-node

    hdfs = hdfs3.HDFileSystem(host='ip-thing.ec2.internal', port=8020,
        pars={"hadoop.security.authentication": "kerberos"})

(i.e., define everything and don't assume configs are found; LIBHDFS3_CONF was *also* set to an xml with the same information, and `kinit` had been run for the user)
With https://github.com/dask/hdfs3/pull/125 you can do

    token = hdfs.delegate_token(user='ubuntu')

Now, even following `kdestroy`, you can do

    hdfs = hdfs3.HDFileSystem(host='ip-thing.ec2.internal', port=8020,
        pars={"hadoop.security.authentication": "token"}, token=token, user='ubuntu')


[I don't mind where the conversation happens, we clearly have a few issues tied together with libhdfs3, hdfs3, knit and dask-yarn).

**Pull request merged**
