### PR TITLE
Configuration refactor

### PR DESCRIPTION
**Pull request by martindurant**
Along the lines of https://github.com/dask/hdfs3/pull/127

### CODE REVIEW

**Comment by martindurant** [comment]
@quasiben , lots of changes here, some of which are important (like the ability to set the location of the staging directory), some of which are cosmetic (like the logs output formatting). Would love your feedback when you have a little time.

@quartox , @kpweiler , this is a precursor to explicit token passing to the containers - but maybe it is already useful to you to clarify what is going on.

**Comment by martindurant** [comment]
Delegated tokens added - please try!

**Comment by quartox** [comment]
It makes it past container startup! But then it runs into a new error. I will post the error message in the issues, since this PR seems to be doing its job well.

**Comment by kpweiler** [comment]
@martindurant sorry for the late response, I've been on vacation! I gave this a try with some very simple code and it didn't toss an errors at me.

```
env = k.create_env(env_name='dev', packages=['dask', 'distributed', 'pandas'])

cmd = 'ls'
```
This implies to me that the env upload is working and that the container can access it, even if my command doesn't actually use it. I'll try something a bit more interesting later.

Thanks!

**Comment by kpweiler** [comment]
I gave the following a shot:

```
env = k.create_env(env_name='dev', packages=['dask', 'distributed', 'pandas'])

cmd = "$PYTHON_BIN -c 'import pandas as pd; print(pd.__version__)'"
```
and I get this error in the containers:

```
/bin/bash: -c: command not found
```

which seems to imply that the PYTHON_BIN env isn't getting set. Am I doing something wrong?

**Comment by martindurant** [comment]
You need to pass the env to `k.start` (perhaps this isn't obvious?). The following works for me. Note that it can be tricky to pass python code like this because of nested quoting.

    k.start('$PYTHON_BIN --version', num_containers=1, env=env)
    # wait
    k.logs()

    ... Python 3.6.2 :: Continuum Analytics, Inc. ...

It is true that `Knit` serves as both an interface to YARN and a single application instance, maybe the two should be split.

^ @kpweiler

**Comment by martindurant** [comment]
I will merge this now, and concentrate on getting the docs up to date, followed by any lingering issues that crop up. Thank you, people, for baring with me, and I hope this can be made into a happy place for yarn-pythoneering.

**Pull request merged**
