### PR TITLE
Tests/Cleanup

### LINKED ISSUE #18: Shorten method names?
Thoughts on removing `_application_` from method names?
-  start_application -> start
-  get_application_logs -> get_logs
-  get_application_status -> get_status
-  kill_application -> kill

?

### PR DESCRIPTION
**Pull request by quasiben**
Resolves #18 and #21 

cc @mrocklin

### CODE REVIEW

**Comment by mrocklin** [comment]
+10

**Comment by mrocklin** [comment]
We might also want to add other tests around status and logs both in correctly working cases to verify that the keywords like `num_containers function properly and in poorly working cases, to verify that failures are obvious from the status and logs.

**Comment by quasiben** [comment]
Finishing that now :)

**Comment by quasiben** [comment]
@danielfrg and I tested this PR against a Cloudera cluster and not only did PR past but latent processes are cleaned as well.  I'm currently investigating yarn-site.xml for (mis)configuration

**Comment by quasiben** [comment]
I'll resolve latent processes in another PR as well has better vCore handling

**Pull request merged**
